### ISSUE TITLE
separate dns names for admin and vpn access

### ISSUE THREAD

**Issue by bert2002** [subspacecommunity/subspace#115]
**Is your feature request related to a problem? Please describe.**
I want to have the admin interface and the vpn running on two different domain names.

**Describe the solution you'd like**
Configure a dns name for the admin interface and one for the vpn (specifically for the config)

**Describe alternatives you've considered**
N/A

**Additional context**
This is important to not expose the admin interface to the public.

**Comment by jack1902** [comment]
@bert2002 are you able to contribute towards this? or is this something for someone else to contribute?

**Comment by bert2002** [comment]
Hi @jack1902, is for someone else to contribute. I am not able to do that much magic :(

**Comment by d3473r** [comment]
Hi, I'm having the same setup: subspace runs in my homenetwork and is accessed via a port forwarding setting on my router.
So my http host is subspace.local.example.com and my vpn host is vpn.example.com.

As I've read through the code I found that this is already possible:
https://github.com/subspacecommunity/subspace/blob/016009fac615ad9587b2945ce3278e50fb67eeee/cmd/subspace/handlers.go#L393-L396

So one just need to set `SUBSPACE_ENDPOINT_HOST: vpn.example.com`
I will open a PR to update the Readme

Regards
