### ISSUE TITLE
Latest version not working on Ubuntu 18.04 on AWS EC2

### ISSUE THREAD

**Issue by imjustd** [subspacecommunity/subspace#121]
**Describe the bug**
The webapp is not reachable at all

**To Reproduce**
try this:
```
docker create \
    --name subspace \
    --restart always \
    --network host \
    --cap-add NET_ADMIN \
    --volume /data:/data \
    --env SUBSPACE_HTTP_HOST="example.com" \
    --env SUBSPACE_HTTP_INSECURE=false \
    --env SUBSPACE_LETSENCRYPT=true \
    --env SUBSPACE_NAMESERVER="1.1.1.1" \
    --env SUBSPACE_LISTENPORT="51820" \
    --env SUBSPACE_IPV4_POOL="10.10.0.0/16" \
    --env SUBSPACE_IPV6_POOL="fd00::10:0:0/64" \
    --env SUBSPACE_IPV4_GW="10.10.0.1" \
    --env SUBSPACE_IPV6_GW="fd00::10:0:1" \
    --env SUBSPACE_IPV6_NAT_ENABLED=1 \
    subspacecommunity/subspace:latest

docker start subspace
```

**Expected behavior**
I expect web admin to be started at the appointed URL

**Screenshots**
I get this screen:
![image](https://user-images.githubusercontent.com/590260/87678614-72412c00-c77b-11ea-8fd0-4a48fe3a2702.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 (updated)
 - Browser Chrome
 - Version 84.0.4147.89 (Official Build) (64-bit)

**Additional context**
I got the version-1.1.1 to work but new ones don't work

**Comment by jack1902** [comment]
relates to #120
