### ISSUE TITLE
SSL Errors

### ISSUE THREAD

**Issue by whizzard-tt** [subspacecommunity/subspace#133]
In the browser the site fails to log giving Secure Connection Failed errors.
I ran the log report and constantly get the following errors:

2020/08/16 20:02:44 http: TLS handshake error from xxx.xxx.xxx.143:34861: autocert: host “xxx.xxx.xxx.2” not permitted by HostPolicy
2020/08/16 20:04:33 http: TLS handshake error from xxx.xxx.xxx.1:27850: acme/autocert: missing server name
2020/08/16 20:15:24 http: TLS handshake error from xxx.xxx.xxx.1:37772: acme/autocert: missing server name
2020/08/16 20:30:44 http: TLS handshake error from xxx.xxx.xxx.1:55774: autocert: host “**xxx.xxx.xxx.xxx** (publicIPaddress)” not permitted by HostPolicy
2020/08/16 20:44:37 http: TLS handshake error from xxx.xxx.xxx.1:53983: acme/autocert: missing server name
2020/08/16 20:57:49 http: TLS handshake error from xxx.xxx.xxx1:65168: tls: first record does not look like a TLS handshake
2020/08/16 21:46:25 http: TLS handshake error from xxx.xxx.xxx:18111: acme/autocert: missing server name
2020/08/16 23:17:46 http: TLS handshake error from xxx.xxx.xxx.1:46534: tls: unsupported SSLv2 handshake received
2020/08/17 00:02:24 http: TLS handshake error from xxx.xxx.xxx.143:4958: EOF
2020/08/17 00:02:45 http: TLS handshake error from xxx.xxx.xxx.1:65451: acme/autocert: unable to satisfy “https://acme-v02.api.letsencrypt.org/acme/authz-v3/6583826515” for domain “subspace.fitzwilliamstone.com”: no viable challenge type found
2020/08/17 00:02:45 http: TLS handshake error from xxx.xxx.xxx.143:5304: autocert: host “xxx.xxx.xxx.2” not permitted by HostPolicy
2020/08/17 01:50:40 http: TLS handshake error from xxx.xxx.xxx.1:32988: acme/autocert: missing server name

xxx.xxx.xxx.1 in the logs represent the edge firewall the host machine sits behind
xxx.xxx.xxx.2 is the host machine

Can you advise on how to resolve this, also is it possible to run it locally without the SSL and public URL?

**Comment by jack1902** [comment]
@whizzard-tt please fill in the bug template
