### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by gchamon** [subspacecommunity/subspace#165]
First of all, I would like to express my deep gratitude for the work done here so far.

This seems to be the only working wireguard UI that integrates with SSO solutions, and thus more suited for production environments in organizations.

However, although there is clear interest from users, I would be more comfortable deploying the project in production if I heard from the contributors. Is this project maintained?

I would also like to volunteer if there is anything I could do, but given the amount of pull requests already opened, I would also like first to know that I wouldn't be devoting time to a deprecated repo.

Thanks once again! Hope to hearing from the team.

**Comment by jack1902** [comment]
@gchamon I used to maintain this but I stopped using it my company. I'd be happy to try and get you permissions to keep it going if you are able to contribute?

@agonbar is an admin on this (I no longer have acces as I removed myself after not using the project for ages)

It might be worth reaching out in the linked slack channels

**Comment by gchamon** [comment]
@jack1902 I will reach out to him at the slack channels. I started using the project and have been maintaining for the past couple of weeks our fork with important patches for us.

I never collaborated on opensource projects before, but I would love to help however I can.

**Comment by metalcated** [comment]
I’d be interested in helping at least perform testing when I have time. I’d
also be able to offer a platform for hosting development environments if
needed.

**Comment by agonbar** [comment]
Sorry for the huge delay, private life got in the way.

I added you both to the group, I need to find a way to let this project be more community maintained while keeping it safe, or at least, to be able to continue without my presence. Right now testing the PR is really time consuming, so any help is deeply appreciated.

I'll try to be more reachable this days and add anyone that wants to help.

**Comment by gchamon** [comment]
@agonbar thanks!
I would like to get to it right away with reviewing other pull requests. Do you have any guideline to start, or an onboarding process? Please let me know how I can help.
