### ISSUE TITLE
Suggestion: Linux & MacOS devices should have "PersistentKeepalive" in their profiles

### ISSUE THREAD

**Issue by unquietwiki** [subspacecommunity/subspace#202]
On a previous Wireguard setup, I found that the Windows client dealt with needing to do keepalives / trying to connect to the VPN server; but the Linux & Mac systems needed to be explicitly told to check, to establish the connection. Documentation I've come across in the past suggests 20 seconds as a good figure.

```
[Peer]
(normal stuff)
PersistentKeepalive = 20
```

**Comment by mrnonz** [comment]
I think it's should built-in subspace and config via ENVIRONMENT variable

Something like
```
- SUBSPACE_PERSISTENT_KEEPALIVE=20
```

20 is mean 20 seconds and If set to 0 is mean disabled.
