### ISSUE TITLE
Corrections to README to account for existing bugs, at least until addressed?

### ISSUE THREAD

**Issue by unquietwiki** [subspacecommunity/subspace#203]
- #158 says you can't define **SUBSPACE_IPV4_GW** or **SUBSPACE_IPV6_GW** without **SUBSPACE_IPV4_POOL** or **SUBSPACE_IPV6_POOL** reverting to default settings. The current README says GW is optional, but new users trying to keep both settings in will run into problems.
- #193 says as of June 2021, **amd64-v1.5.0** was the latest Docker tag, but **latest** was still pointing to an older branch; causing **SUBSPACE_NAMESERVERS** to not be recognized. Docker Hub was only listing **latest** and not the branches as of Aug 2021.
- Didn't see a bug on this, but noticed **SUBSPACE_IPV6_NAT_ENABLED=true** as an example in the current README. That can also be set to 0, as well as **SUBSPACE_IPV4_NAT_ENABLED**; but setting both to 0 or false will cause errors saying you have to have at least one NAT turned on. That behavior only makes sense if **SUBSPACE_ALLOWED_IPS** is not default.

**Edit:** I need to emphasize this isn't nitpicking; the software itself is fantastic (the G-Suite integration worked like a charm). These gotchas are the obstacles I ran into getting my own environment going, that I'm sure other new users will be running into as well.

**Comment by gchamon** [comment]
Published a note to address the docker tag issue. Currently reviewing a PR that might fix https://github.com/subspacecommunity/subspace/issues/158

> Didn't see a bug on this, but noticed SUBSPACE_IPV6_NAT_ENABLED=true as an example in the current README. That can also be set to 0, as well as SUBSPACE_IPV4_NAT_ENABLED; but setting both to 0 or false will cause errors saying you have to have at least one NAT turned on. That behavior only makes sense if SUBSPACE_ALLOWED_IPS is not default.

Could you open a separate issue for this?

**Comment by unquietwiki** [comment]
> Published a note to address the docker tag issue. Currently reviewing a PR that might fix #158
> 
> > Didn't see a bug on this, but noticed SUBSPACE_IPV6_NAT_ENABLED=true as an example in the current README. That can also be set to 0, as well as SUBSPACE_IPV4_NAT_ENABLED; but setting both to 0 or false will cause errors saying you have to have at least one NAT turned on. That behavior only makes sense if SUBSPACE_ALLOWED_IPS is not default.
> 
> Could you open a separate issue for this?

@gchamon done! Thanks!
