### ISSUE TITLE
Use of bash scripts that hard-code wg0 makes this unusable on macOS

### ISSUE THREAD

**Issue by nhi-vanye** [subspacecommunity/subspace#22]
macOS requires a different naming convention for wireguard interfaces.

Rather than use bash scripts, has there been any discussion on using wireguard-go directly ?

**Comment by agonbar** [comment]
This project was funded more as an interface for existing wireguard in a company. But, a version with self-contained wireguard clould be a solution for many of the problems that people have like using it in OSX or Kubernetes/Swarms.  Maybe someone cloud fork the project into a version like that.

**Comment by nhi-vanye** [comment]
Let me think about that a bit... Go is not my strong point...

My use case is to bring WIreguard into my networks. In this case "my networks" start at my home lab (mix of very large VMware servers + Macs + synology + Linux) + IoT smart home (being built) . But I'd also be interested in replacing our existing VPN (site-to-site and remote access) with a more distributed model - remote working has made that a more interesting use case.

I did look at tailscale - very convenient from end-user. but too early and its unclear how access control works without spending more than my existing VPNs.

I also want a way to manage which peers can see which other peers - my use case here is to allow a remote (open source) colleague direct access to one of my VMs without allowing them to access the rest of my (home) network. And doing it in a scalable way so that I'm not having to spend too much time administering it as people change devices/new people get involved/old people retire/etc.

**Comment by gavinelder** [comment]
Hi @nhi-vanye I am using Subspace on macOS catalina using https://github.com/WireGuard/wireguard-apple/releases what aspect exactly is making it unusable ?

**Comment by gavinelder** [comment]
@nhi-vanye can you advise if this still an issue or I shall close this?
