### ISSUE TITLE
Unable to get SSO with JumpCloud working

### ISSUE THREAD

**Issue by jack1902** [subspacecommunity/subspace#24]
TL;DR has anyone got this working with JumpCloud?

I have been trying to get SAML SSO Setup with JumpCloud as the IDP (Identity provider) and this being the SP (Service provider).

Using this with google, it works fine, but with JumpCloud i keep getting SAML Errors. Has anyone managed to get this to work.

i have raised this in the original repo but i no longer know if that is maintained?
https://github.com/subspacecloud/subspace/issues/66

**Comment by agonbar** [comment]
I don't personally use JumpCloud and Google seems to work fine, as far as I know, the original subspacecloud is abandoned by the company. If you happen to find a solution, please report and I will make any needed changes!

**Comment by jack1902** [comment]
@agonbar Thanks, i can get Google to work just fine but i am trying to get JumpCloud to work (i've been looking into the `crewjam/saml` library to see if there is anything extra i need to do in regards to JumpCloud. I might potentially update the dependancy to a newer version in the future but i am a python dev so Golang is fairly new to me

**Comment by jack1902** [comment]
Wow, so i managed to get it to work i had to enable these toggle boxes within JumpCloud (enable the application for a group of users) and this:

<img width="839" alt="Screenshot 2020-05-08 at 13 00 22" src="https://user-images.githubusercontent.com/39212456/81403717-efbd4000-912b-11ea-9dbf-521c67688822.png">
<img width="468" alt="Screenshot 2020-05-08 at 12 59 36" src="https://user-images.githubusercontent.com/39212456/81403723-f21f9a00-912b-11ea-8d02-f02548825d21.png">


I will open a PR to extend the basic html page to include a link to the relevant documentation to configure JumpCloud for this amazing application (hoping it will be merged)
