### ISSUE TITLE
Add ability to toggle default masquerade

### ISSUE THREAD

**Issue by jack1902** [subspacecommunity/subspace#28]
### Description

Make it possible to disable the automatic iptables masquerade settings so that the user of subspace can have more control over the connections to wireguard 

Why?
I would like clients to be able to connect to the server after they have acquired a Wireguard.conf  from `subspace`, but not be able to use the tunnel until they have authenticated via a push notification. Once they have done this second step of authentication, i will then update the `iptables` to allow their client ip through

This is done by monitoring the `last_handshake` from `wg show wg0 dump` for each ip address and mapping it to the relevant client in order to send a push notification

## Desired Change

Make it possible to disable the iptables `masquerade` settings with a flag/env variables

**Comment by squat** [comment]
This can be closed now, right?
