### ISSUE TITLE
build broken

### ISSUE THREAD

**Issue by universam1** [subspacecommunity/subspace#35]
current master does not build:

```
╰─➤  go build . 
# github.com/subspacecommunity/subspace
./mailer.go:91:27: undefined: AssetNames
./mailer.go:96:13: undefined: Asset
./web.go:109:27: undefined: AssetNames
./web.go:114:13: undefined: Asset
./web.go:253:12: undefined: Asset
./web.go:258:13: undefined: AssetInfo
```

**Comment by universam1** [comment]
this suggested PR actually solves it locally as well: https://github.com/subspacecommunity/subspace/pull/31/files

**Comment by gavinelder** [comment]
Yeah there is a small syntax error in the build, I will look at making a PR with some docs today.

**Comment by agonbar** [comment]
Yes, the pull was merged so I close this one, tanks for the contributions!
