### ISSUE TITLE
Proposal - Gophers Slack. 

### ISSUE THREAD

**Issue by gavinelder** [subspacecommunity/subspace#41]
Hey I think it may be a good idea to make a channel on [Gopher Slack](https://gophers.slack.com/join/shared_invite/zt-eily9qic-LmUga18uk180u8sunc1rVw#/) Specifically for subspace it would be a way to have ad-hoc discussions and potentially help drive up maintainers.

**Comment by gavinelder** [comment]
So there is now a slack channel called #subspace on Slack feel free to come join

**Comment by agonbar** [comment]
Should we set this anywhere else?

**Comment by gavinelder** [comment]
Yeah will draft a PR :)
