### ISSUE TITLE
Proposal CI

### ISSUE THREAD

**Issue by gavinelder** [subspacecommunity/subspace#43]
Hi I suggest we sign up to something like CircleCI or Travis for the organisation from that we can do CI linting using golang-ci lint and confirm docker builds are correct. 

Any thoughts on which service / checks we should do on PRs ?

**Comment by jack1902** [comment]
I would personally try out Github Actions, as its built in and has come a long way compared to where it used to be

**Comment by gavinelder** [comment]
@agonbar can you set me up with repo admin to setup ?

**Comment by agonbar** [comment]
@gavinelder Permission given, my experience tells me that CircleCI is a good option, I haven't tried Github Actions, but maybe is a good option to keep everything integrated in the same place.
