### ISSUE TITLE
HOWTO connect from Desktop Linux 

### ISSUE THREAD

**Issue by shaheenkdr** [subspacecommunity/subspace#46]
Provided I have the server configured and running, how do I connect to the server from my local machine ? Any Howto's on that ?

**Comment by krisbolton** [comment]
There appear to be instructions built-in once the server is running. I can't be specific and provide them as I haven't used subspace. See the left bottom image on the repo readme, it lists instructions with links within the server UI.

**Comment by gavinelder** [comment]
Hi @shaheenkdr as @krisbolton eluded to the setup process is guided in the server itself as part of the client for example 

![image](https://user-images.githubusercontent.com/1226100/82454796-1ffccb00-9aaa-11ea-9891-960bdfd35d23.png)

![image](https://user-images.githubusercontent.com/1226100/82454835-2d19ba00-9aaa-11ea-80a8-5e09f237fde7.png)
