### ISSUE TITLE
Ability to cap the number of Configurations a single user can have

### ISSUE THREAD

**Issue by jack1902** [subspacecommunity/subspace#54]
---
name: Feature request
about: Ability to cap number of configurations a user can have
---

**Is your feature request related to a problem? Please describe.**
It would be nice to have the ability to configure the number of active configurations a single user can have from the settings page.

**Describe the solution you'd like**
The ability to configure the number of active configurations a single user of `subspace` can have at any given time. This would not apply to an `admin` user but again this could also be configurable.

**Describe alternatives you've considered**
N\A

**Comment by gavinelder** [comment]
This is defined as https://github.com/subspacecommunity/subspace/blob/2d46b6941cb8b2a8ffce3169c51386022ac15443/handlers.go#L22 do you want to expose this as a flag or wait for this to be moved into config ?

**Comment by jack1902** [comment]
Rather move it to a config file which is manipulated from the admin settings page. Flags are messy, I'd rather have `subspace` as it's own thing which is controlled through a settings file / admin panel.

Curious to know what others would prefer though

**Comment by Fastidious** [comment]
I agree with it to be in a configuration rather than exposed as a flag.

**Comment by jack1902** [comment]
This already exists, so going to close this issue
