### ISSUE TITLE
Expose an API so users can be deleted without having to log in to subspace

### ISSUE THREAD

**Issue by jack1902** [subspacecommunity/subspace#55]
---
name: API `/delete/`
about: Suggest an idea for this project
title: ''
labels: ''
assignees: ''

---

**Is your feature request related to a problem? Please describe.**
It would be great if it was possible to delete a user from `subspace` without having to go to a webpage and use an endpoint similar to `/delete`

**Describe the solution you'd like**
Ability to send data to an endpoint such as `/delete_user` in order to be able to script elements of a JML process. Subspace suffers currently with the following:

- A user can sign in to subspace, and can create a certificate
- User leaves the company but their certificate is still valid
- Admin user MUST log on to subspace in order to remove a users certificates.

If the above could be automated by exposing an endpoint then this process would be simpler for Admins of `subspace`. This would need to be protected by an `API Key` which should be tied to Admins.

**Describe alternatives you've considered**
Log on to `subspace` as an admin and remove the user and their configurations

**Comment by gavinelder** [comment]
@jack1902 you got this one or want some help here ?

**Comment by hongkongkiwi** [comment]
It would be great to do all functions via an API actually, create user, delete user etc

**Comment by jack1902** [comment]
I'm probably not going to implement this as i no longer use this project, i'm happy to review others work but finding the time for this is not my highest priority
