### ISSUE TITLE
Feature Request : Blocking Ads

### ISSUE THREAD

**Issue by shaheenkdr** [subspacecommunity/subspace#56]
Similar to Pi Hole , if a network wide Ad blocker could be integrated and the option to  turn it ON and OFF would be a nice to have feature. Not sure if its beyond the scope of this project.

**Comment by Fastidious** [comment]
I’ll say beyond the scope.

**Comment by jack1902** [comment]
So as you are looking at a DNS level AD blocker, such as PiHole you could configure PiHole on the same server and set piholes ports to 53 for DNS and 8080 for it's webui.

https://github.com/subspacecommunity/subspace/blob/4b111f801c0007730f95aca40d7b8bade5523bca/handlers.go#L426-L430

From the above snippet you can see that the clients configuration is setting DNS as the wireguard server, but if you have pihole or an equivalent running then this can be used instead
