### ISSUE TITLE
dnsmasq: failed to create listening socket for port 53: Address already in use

### ISSUE THREAD

**Issue by thisadamis** [subspacecommunity/subspace#57]
I get this error in the docker logs after a fresh install of ubuntu 18.04.

dnsmasq: failed to create listening socket for port 53: Address already in use

What am I doing wrong?

**Comment by jack1902** [comment]
So this PR #48 adds a piece to the README which I'll break out to the wiki to have a "common problems" 

This snippet is from the PR:

```
# Disable systemd-resolved if it blocks port 53.
systemctl disable systemd-resolved
systemctl stop systemd-resolved
```
