### ISSUE TITLE
Allow iptables rules to be disabled

### ISSUE THREAD

**Issue by gilesw** [subspacecommunity/subspace#61]
Sometimes you might want to manage iptables yourself and be using a firewall that clears all current rules.

**Comment by jpbostic** [comment]
FWIW, I found a little workaround until proper options are merged for doing this...

1. Create a script iptables-noop
`````
#!/bin/sh

/bin/true
`````
2. Be sure to make it executable:
`````
chmod a+x iptables-noop
`````
3. In the args to run docker, add this (tweaking to fit your script path):
`````
--volume /etc/systemd/other/iptables-noop:/sbin/xtables-legacy-multi
`````

The iptables exe in the docker image is just a symlink to /sbin/xtables-legacy-multi, so if that has been overwritten with this do-nothing script, calls to iptables inside the container will do nothing, successfully (see "man true"), to keep docker and entrypoint scripts happy.
