### ISSUE TITLE
Let's Encrypt Account creation on ACMEv1 is disabled

### ISSUE THREAD

**Issue by bobbyiliev** [subspacecommunity/subspace#70]
When starting a fresh instance of the Subspace Docker container it is unable to generate a Let's Encrypt SSL certificate due to ACMEv1 and as of now Let's Encrypt supports only ACMEv2 only.

Exact error from the logs:

```
2020/05/23 18:56:08 http: TLS handshake error from 123.123.123.123:62878: 403 urn:acme:error:unauthorized: Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://c
ommunity.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.
2020/05/23 18:56:08 http: TLS handshake error from 123.123.123.123:62879: acme/autocert: missing certificate
```

1. Create a fresh new Ubuntu 18.04 server
2. Follow all of the steps from the documentation
3. Start a new container
4. Check the logs

**Comment by gavinelder** [comment]
Hi what image are you using? 

I believe this is resolved in master.

**Comment by bobbyiliev** [comment]
Yes indeed, I was using an older image! Thanks!
