### ISSUE TITLE
http-insecure ignored

### ISSUE THREAD

**Issue by theonlydoo** [subspacecommunity/subspace#77]
**Describe the bug**
Trying to bind to http://localhost w/o https, relying on a proper reverse proxy to offload SSL and send traffic to subspace. Resulting on a https redirection each time

**To Reproduce**
```bash
$ git clone https://github.com/subspacecommunity/subspace.git \
&& cd subspace \
&& go get -d \
&& make \
&& go install \
&& /root/go/bin/subspace -datadir /data/subspace   -http-insecure -http-addr 127.0.0.1:80 -http-host foo.bar.baz -letsencrypt false
INFO[0000] Subspace version:  https://foo.bar.baz/ 
```

and then:
```bash
$ curl 127.1
<a href="https://foo.bar.baz/">Found</a>.

$ curl 127.1 -i
HTTP/1.1 302 Found
Content-Type: text/html; charset=utf-8
Location: https://foo.bar.baz/
Date: Wed, 27 May 2020 14:38:34 GMT
Content-Length: 43

<a href="https://foo.bar.baz/">Found</a>
```
**Expected behavior**
Not being redirected to https

**Desktop (please complete the following information):**
 - OS: debian 10

**Comment by jack1902** [comment]
This works for me:

```
subspace -datadir $(pwd)/data -http-insecure -http-addr 127.0.0.1:80 -http-host localhost -letsencrypt=false
```

notice:
`-letsencrypt=false` 

The = is required by golang flags. The default by subspace is `true` which requires the caller to specify `=false` in order for it to be set to `false`

> Boolean flags: A boolean flag will parse to a value of true if the flag has been set and no user input was provided. Using a default value of false will allow you to determine if the flag was set. A boolean flag may be set with user input using an “=”, but it's not required (see package docs for details).

**Comment by theonlydoo** [comment]
indeed, works using `=` thanks!
