### ISSUE TITLE
G Suite SAML APP : app_not_configured_for_user

### ISSUE THREAD

**Issue by clementperon** [subspacecommunity/subspace#80]
Hi,

I have added the IDP Metadata XML generated with the correct ACS URL and Entity ID.

But unfortunately when I try to signin with the google account i have the following error :

Error: app_not_configured_for_user

Service is not configured for this user.

I have configured the SAML APPs:
Name ID : Basic information / Primary Email
Name ID Format: UNSPECIFIED

The SAML APPs is "On for everyone" and the Subspace docker is behind an Nginx Reverse proxy

Thanks for your help,
Clement

**Comment by bruse** [comment]
As @jack1902 mentions, make sure you enable the users or the groups (or even enable for all users) at the admin.google.com status page for your SAML app.

When I enabled all users, it told me it might take up to 24 hours for the changes to propagate. It ended up taking a few hours.

**Comment by clementperon** [comment]
Hi thanks for your replies @bruse and @jack1902 ,

I have created the SAML App more than 2 days ago.
The status says: "On for everyone"

I have copy paste the ACS And Entity ID:
It looks like this
ACS: https://mydomain.toto/saml/acs
Entity ID: https://mydomain.toto/saml/metadata
Start URL: *empty*
Certificate : Google_2024_xxx
Signed response  : unchecked
Name ID: Basic information / Primary email
Name ID format: Unspecified

My domain mail is clement@mydomain.tata

I will try to create a new one,
thanks for your help

**Comment by pysen** [comment]
If we decode your SAMLRequest body with the [Google Decoder](https://toolbox.googleapps.com/apps/encode_decode) in SAML Decode mode the request has these properties:

`<saml:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">http://subspace.*.*.ht/saml/metadata</saml:Issuer>`

The reason for the http:// protocol in the SAML request and not https:// is due to the **SUBSPACE_HTTP_INSECURE** environment variable is set to **false**. Setting it to **true** will make the application request it using https:// instead.

@clementperon Perhaps a good idea to edit out a part of the request body as it contains a DNS entry.

**Comment by clementperon** [comment]
Hi @pysen,

Thanks for noticing, I have removed the request details.

Indeed the subspace is configured as insecured as I am behind a nginx proxy.
Maybe I should keep it secure and forward the traffic in TLS inside my network instead of plain http?

Regards,
Clement

**Comment by pysen** [comment]
@clementperon I've got a similar setup with subspace behind a reverse proxy (traefik) to handle TLS termination and with **SUBSPACE_HTTP_INSECURE** set to **false** I can still hit the HTTP endpoint. Not sure if this is a feature or bug though.

**Comment by clementperon** [comment]
@pysen  did you force the http to redirect to https ? 

Is it not a bit unsecure to reach an endpoint in http ?

Thanks 
Clement

**Comment by pysen** [comment]
@clementperon I don't have the HTTP endpoint exposed outside the network perimeter in my setup.

External facing Traefik reverse proxy (with basic auth on **https://subspace.example.com/signin**) -> 
forwards the request to the Subspace host Traefik/NGINX on my local network ->
Subspace HTTP endpoint on same host as the Traefik/NGINX

I would remove the middle Traefik/NGINX if Subspace would support Let's Encrypt certificates using the DNS challenge method but this would require the app to have access to your DNS provider's API which can be an unwanted permissions for a VPN software.

**Comment by clementperon** [comment]
@pysen 

I have switched to Traefik, and make the forward in https using insecureSkipVerify.
      - "--serversTransport.insecureSkipVerify=true"

Everythings works fine now !

Thanks

**Comment by nrukavkov** [comment]
The same problem. subspace is configured for using redirect http->https. In G suite saml application allows to login gor any user
