### ISSUE TITLE
mkdir /etc/sv/dnsmasq error on starting Docker container

### ISSUE THREAD

**Issue by helix90** [subspacecommunity/subspace#82]
Ubuntu 18.04
Docker Engine 19.03.11

docker logs end with:
"mkdir: can't create directory '/etc/sv/dnsmasq': No such file or directory"

1. install ubutnu 18.04
2. install docker-ce
3. follow README for 'docker create' with the addition of lines for wg libraries from Issue #72 
4. docker start subspace
5. docker logs subspace

Output:
'''
...
+ ip addr add fd00::10:97:1/64 dev wg0
+ wg setconf wg0 /data/wireguard/server.conf
+ ip link set wg0 up
+ test -d /etc/sv/dnsmasq
+ cat
+ mkdir /etc/sv/dnsmasq
mkdir: can't create directory '/etc/sv/dnsmasq': No such file or directory
'''

**Comment by gavinelder** [comment]
Hi @helix90 this should now be resolved on master can you try again , you may need to recreate the docker image to pull the latest.
