### ISSUE TITLE
Installation stuck at [ /usr/local/bin/entrypoint.sh: line 157: wg: not found ]

### ISSUE THREAD

**Issue by lucatze** [subspacecommunity/subspace#84]
**Describe the bug**
When running the docker container for the first time, the boot up stops at 

`/usr/local/bin/entrypoint.sh: line 157: wg: not found`

**To Reproduce**
Follow the installation procedure of subspace

**Expected behavior**
No error in logs

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04, fresh installation on a Linode VPS.

**Comment by rsinyakov** [comment]
Try this
https://github.com/subspacecommunity/subspace/issues/72#issuecomment-633289750

**Comment by lucatze** [comment]
> Try this
> [#72 (comment)](https://github.com/subspacecommunity/subspace/issues/72#issuecomment-633289750)

Thank you, that helped.
