### ISSUE TITLE
Max profiles for admin

### ISSUE THREAD

**Issue by vojta7** [subspacecommunity/subspace#91]
**Describe the bug**
Admin is limited to 10 profiles.

**To Reproduce**
1. Go to subspace page
2. Login as admin
3. Create 10 profiles
4. Try to create 11th one, this will fail

**Expected behavior**
Admin has no limit on the number of profiles.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser firefox
 - Version 77

**Additional context**
[profileAddHandler](https://github.com/subspacecommunity/subspace/blob/f6732cf6c35a6e81dd9403631aa1b7dfb98e28d1/handlers.go#L336) is expecting form parameter admin to be yes, but my browser is not sending admin at all. I can manually edit HTTP request to send these parameters:
```
name=new_user&platform=yes&admin=yes
```
I can add as many users as I want with this, this does not seem secure at all.

**Comment by agonbar** [comment]
I see two options here, either remove the limit for now and leave an issue pending a rework from the back or we try to implement it with the current backend.

My vote goes to remove the limit for now and wait for the rework, but I would like to have more opinions than mine before proceeding.

**Comment by gavinelder** [comment]
Happy with remove.
